# directories and paths
executable_path: '/workspace/envs/helios/helios'
root_dir: '${hydra:runtime.cwd}'
dataset_name: 'munich'
input_dir: '/workspace/data/munich/obj/instances_LocalCRS/'
output_dir: '${root_dir}/outputs/${dataset_name}_als/'
object_suffix: '.obj'
cloud_filename: '${output_dir}/stripmission_point.laz'

# survey settings
create_survey: true
move_speed: 70
pulse_frequency: 1500000
scan_angle: 30
scan_frequency: 150
time_interval: 0.01
platform: 'sr22'
scanner: 'leica_hyperion-ii'
bbox_min: [1770, -705]
bbox_max: [2050, -415]
strip_interval: 160
flight_height: 400

# scene settings
create_scene: false
scale: 1  # 1000 for Helsinki
offset: 0;0;0  # Munich Global: CRS bounding box (by vertices): Min: dvec3(676042.210000, 5326481.160000, 481.400000), Max: dvec3(702063.376000, 5346739.302000, 802.890000)

# runtime settings
seed: 1117
threads: 28
quiet: false

# hydra settings
hydra:
  run:
    dir: '${output_dir}'
  verbose: false
defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog
