# Default configuration for the project.
# Values can be overriden by respective dataset configurations.

# default settings
defaults:
  - _self_
  - dataset: berlin
  - override hydra/job_logging: custom
  - override hydra/hydra_logging: colorlog

# paths settings
helios_executable: '/workspace/envs/helios/helios'
root_dir: '${hydra:runtime.cwd}'

# runtime settings
seed: 1117
threads: 32
quiet: false
chunk_size: 500000000

# hydra settings
hydra:
  run:
    dir: '${output_dir}'
  verbose: false
